name: "Test"

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_FEATURE_FLAGS: "dependencygraph"

permissions:
  contents: "write"

jobs:
  publish:
    runs-on: "windows-latest"

    steps:
      - id: variables
        name: Generate Variables
        run: |
          $name = ("${{ github.event.repository.name }}".Substring(4) -split '-') | ForEach-Object { $_.Substring(0, 1).ToUpper() + $_.Substring(1).ToLower() } | Join-String -Separator ' ';
          echo "name=$name" >> $env:GITHUB_OUTPUT

          if ("${{ github.event.base_ref }}" -match '^v[0-9]+.[0-9]+.[0-9]+$') {
            echo "is_test=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "is_test=false" >> $env:GITHUB_OUTPUT
          }

      - name: View Release Name
        run: |
          echo "Release name is ${{ steps.variables.outputs.name }}"

      - name: Is Test
        run: |
          echo "Test? ${{ steps.variables.outputs.is_test }}"